/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4rOcRX42nzv
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function LoginPage() {
  return (
    (<div
      key="1"
      className="min-h-screen bg-gray-100 flex items-center justify-center">
      <Card className="w-96">
        <CardHeader>
          <CardTitle className="text-2xl">Login</CardTitle>
          <CardDescription>Enter your email and one-time passcode to login to your account.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="passcode">One-Time Passcode</Label>
            <div className="space-y-2">
              <Label htmlFor="passcode">One-Time Passcode</Label>
              <div className="flex space-x-2">
                <Input
                  className="w-8 text-center"
                  id="passcode-1"
                  maxLength="1"
                  placeholder="1"
                  required
                  type="text" />
                <Input
                  className="w-8 text-center"
                  id="passcode-2"
                  maxLength="1"
                  placeholder="2"
                  required
                  type="text" />
                <Input
                  className="w-8 text-center"
                  id="passcode-3"
                  maxLength="1"
                  placeholder="3"
                  required
                  type="text" />
                <Input
                  className="w-8 text-center"
                  id="passcode-4"
                  maxLength="1"
                  placeholder="4"
                  required
                  type="text" />
                <Input
                  className="w-8 text-center"
                  id="passcode-5"
                  maxLength="1"
                  placeholder="5"
                  required
                  type="text" />
                <Input
                  className="w-8 text-center"
                  id="passcode-6"
                  maxLength="1"
                  placeholder="6"
                  required
                  type="text" />
              </div>
            </div>
          </div>
        </CardContent>
        <CardFooter className="space-y-2">
          <Button className="w-full">Sign in</Button>
          <Button className="w-full bg-[#4285F4] text-white">
            <div className="flex items-center justify-center">
              <ChromeIcon className="w-4 h-4 mr-2" />
              Continue with Google
            </div>
          </Button>
        </CardFooter>
      </Card>
    </div>)
  );
}


function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}
